Repository LG-Uplus-Movie-SNS-PICKY/PICKY-BE, pull requests merged in 2024-12, with the labels that each got.

#47 [BE][UP-75] 영화 Create / Read API
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieReq.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewLikeRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/FilmCrewRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/GenreRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieBehindVideoRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieGenreRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movieworker/MovieWorkerRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewLikeController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#49 [BE][UP-49] 게시글, 댓글 CREATE 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardManagingService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardManagingUseCase.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardCommentReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardCommentResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardContentReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddOrDeleteBoardLikeResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/DeleteBoardCommentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/DeleteBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetAllBoardComments.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetBoardContentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetMovieRelatedBoardsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/UpdateBoardReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/UpdateBoardResp.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardCommentRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardContentRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardLikeRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/board/Board.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardComment.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardContent.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardContentType.java
  src/main/resources/properties/jpa.yml
Labels: FEAT

#53 [BE][UP-66] 한줄평 READ 구현
  src/main/java/com/ureca/picky_be/base/TestController.java
  src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewUseCase.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewReq.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewQueryRequest.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/ReadLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/UpdateLineReviewReq.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/UpdateLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/jpa/lineReview/LineReview.java
  src/main/java/com/ureca/picky_be/jpa/lineReview/SortType.java
Labels: FEAT

#57 [BE][UP-85] 한줄평 & 한줄평 좋아요 READ lastCreatedAt 커서 추가
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
Labels: FEAT

#55 [BE][UP-49] 게시글 Update 구현
  src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java
  src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardManagingService.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardContentRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/jpa/board/Board.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardContent.java
Labels: FEAT

#58 [BE][UP-84] 영화 추천 리스트 (임시), 영화 top 10 리스트 (임시), 장르별 영화 조회, 영화 좋아요
  src/main/java/com/ureca/picky_be/base/TestController.java
  src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java
  src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java
  src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java
  src/main/java/com/ureca/picky_be/base/business/auth/OAuth2UseCase.java
  src/main/java/com/ureca/picky_be/base/business/auth/dto/LoginUserResp.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieReq.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieByGenreReq.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieResp.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/UpdateMovieReq.java
  src/main/java/com/ureca/picky_be/base/implementation/auth/GoogleManager.java
  src/main/java/com/ureca/picky_be/base/implementation/auth/KakaoManager.java
  src/main/java/com/ureca/picky_be/base/implementation/auth/NaverManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieLikeRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/auth/OAuth2Controller.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/jpa/movie/Movie.java
  src/main/java/com/ureca/picky_be/jpa/movie/MovieLike.java
Labels: FEAT

#62 [BE][UP-101] 프론트 연결 위한 백엔드 소셜 로그인 코드 수정 및 장르 리스트 전송 api
  src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java
  src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java
  src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java
  src/main/java/com/ureca/picky_be/base/business/auth/OAuth2UseCase.java
  src/main/java/com/ureca/picky_be/base/business/auth/dto/LoginUserResp.java
  src/main/java/com/ureca/picky_be/base/business/auth/dto/TokenResp.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetGenres.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/UpdateUserReq.java
  src/main/java/com/ureca/picky_be/base/implementation/auth/GoogleManager.java
  src/main/java/com/ureca/picky_be/base/implementation/auth/KakaoManager.java
  src/main/java/com/ureca/picky_be/base/implementation/auth/NaverManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/OAuth2DtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/auth/OAuth2Controller.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/jpa/user/User.java
Labels: FEAT

#60 [BE][UP-49] Board Update 내용(Context)와 스포일러 여부(isSpoiler)만 수정되도록 수정
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/UpdateBoardReq.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/jpa/board/Board.java
Labels: FEAT

#65 [BE][UP-106] 쿼리 최적화를 위한 작성자 닉네임 필드 추가
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/jpa/board/Board.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardComment.java
  src/main/java/com/ureca/picky_be/jpa/lineReview/LineReview.java
Labels: FEAT

#66 [UP-105] SecurityContextHolder에 유저 정보 추가
  src/main/java/com/ureca/picky_be/base/implementation/auth/AuthManager.java
  src/main/java/com/ureca/picky_be/global/web/CustomUserDetails.java
  src/main/java/com/ureca/picky_be/global/web/CustomUserDetailsService.java
Labels: FEAT

#68 [BE][UP-110] 작성자 필드 추가되도록 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
Labels: FEAT

#69 [BE][UP-94] 한줄평 수정
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/ReadLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/UpdateLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
Labels: FEAT

#71 [BE][UP-11] 소셜로그인 프론트 연결 version2
  src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java
  src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java
  src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java
Labels: FIX

#72 [BE][UP-49] 영화에 대한 무비로그 조회 API 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardContentPOJO.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#74 [BE][UP-49] 최신 무비로그 조회 API 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
Labels: FEAT

#75 [BE][UP-117] 닉네임 중복검사, 회원가입시 영화 리스트 전송 api
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/MoviePreferenceResp.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/GetMoviesForRegisReq.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/GetMoviesForRegisResp.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/GetNicknameValidationResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/user/UserRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
Labels: FEAT

#77 [BE][UP-49] 댓글 조회 API 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardCommentReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardCommentResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardContentReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/AddOrDeleteBoardLikeResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardCommentProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/DeleteBoardCommentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/DeleteBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetAllBoardComments.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetBoardContentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/GetMovieRelatedBoardsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/UpdateBoardReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/UpdateBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/AddBoardReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/AddBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/DeleteBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetMovieRelatedBoardsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/UpdateBoardReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/UpdateBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/AddBoardCommentReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/AddBoardCommentResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/DeleteBoardCommentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/GetAllBoardCommentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/contentDto/AddBoardContentReq.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/contentDto/GetBoardContentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/likeDto/AddOrDeleteBoardLikeResp.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/jpa/board/Board.java
Labels: FEAT

#79 [BE][UP-125] 게시글 삭제 API 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/board/Board.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardComment.java
  src/main/java/com/ureca/picky_be/jpa/config/IsDeleted.java
  src/main/java/com/ureca/picky_be/jpa/lineReview/LineReview.java
  src/main/java/com/ureca/picky_be/jpa/movie/Movie.java
  src/main/java/com/ureca/picky_be/jpa/user/User.java
Labels: FEAT

#81 [BE][UP-126] 댓글 삭제 API 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/DeleteBoardResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetMovieRelatedBoardsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/AddBoardCommentResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/DeleteBoardCommentsResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/contentDto/GetBoardContentsResp.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardCommentRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
Labels: FEAT

#84 [BE][UP-133] BoardController pathvariable, requestparam 수정
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
Labels: FEAT

#86 [BE][UP-134] Spring Security 경로 허용 및 preflight 설정
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewLikeController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/config/WebConfig.java
Labels: FIX

#88 [BE][UP-134] 보안 수정
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
Labels: FIX

#89 [BE][UP-134] 보안 수정
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
Labels: FIX

#87 [BE][UP-132] 게시글 좋아요 기능 구현
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardLikeRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardLike.java
Labels: FEAT

#91 [BE][UP-132] 보안 설정 (닉네임 중복 검사)
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
Labels: FIX

#92 [BE][UP-123] 플레이리스트 조회
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieProjection.java
  src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistService.java
  src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistUseCase.java
  src/main/java/com/ureca/picky_be/base/business/playlist/dto/GetPlaylistProjection.java
  src/main/java/com/ureca/picky_be/base/business/playlist/dto/GetPlaylistResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/playlist/PlaylistRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/playlist/PlaylistController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#93 [BE][UP-123] 플레이리스트 추가를 위한 영화 리스트 페이지네이션 조회, 플레이리스트 추가
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistService.java
  src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistUseCase.java
  src/main/java/com/ureca/picky_be/base/business/playlist/dto/AddPlaylistReq.java
  src/main/java/com/ureca/picky_be/base/business/playlist/dto/AddPlaylistResp.java
  src/main/java/com/ureca/picky_be/base/business/playlist/dto/UpdatePlaylistReq.java
  src/main/java/com/ureca/picky_be/base/business/playlist/dto/UpdatePlaylistResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/playlist/MoviePlaylistRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/playlist/PlaylistRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/admin/AdminPlaylistController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/playlist/PlaylistController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/playlist/Playlist.java
Labels: FEAT

#97 [BE][UP-out_of_number] 임시 토큰 발급 api
  .github/workflows/picky-backend-ci-cd.yml
  .gitignore
  src/main/java/com/ureca/picky_be/base/presentation/controller/TempController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: FEAT

#98 [BE][UP-146] 영상&사진 업로드 인프라 구축 및 board에 사진&영상 업로드 로직 추가
  .github/workflows/picky-backend-ci-cd.yml
  .gitignore
  build.gradle
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/AddBoardReq.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/content/ImageManager.java
  src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java
  src/main/java/com/ureca/picky_be/base/implementation/content/VideoManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/presentation/ContentController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/TempController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/config/S3Config.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/config/SwaggerConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/web/JwtTokenProvider.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardContentType.java
  src/main/resources/application.yml
Labels: FEAT

#99 [BE][UP-146] 회원가입시 유저 프로필사진 설정 api
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/RegisterUserReq.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/UpdateUserReq.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/user/User.java
  src/main/resources/static/files/image/tmp.txt
  src/main/resources/static/files/profile/temp.txt
  src/main/resources/static/files/video/temp.txt
Labels: FEAT

#101 [BE][UP-146] 유저 정보 조회할 때 이메일 가져오기
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/GetUserResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/auth/OAuth2Controller.java
Labels: FEAT

#102 [BE][UP-146] 무비로그 조회에 영상 및 사진 조회 임시 링크 발급
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardContentPOJO.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/contentDto/BoardContentWithBoardId.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/contentDto/GetBoardContentResp.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardContentRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
Labels: FEAT

#103 [BE][UP-146] 회원가입 절차 단순화, 로그인시 유저 role 반환, 유저 조회시 presignUrl로 프로필 전송
  src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java
  src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java
  src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java
  src/main/java/com/ureca/picky_be/base/business/auth/dto/TokenResp.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/GetUserResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/OAuth2DtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
Labels: FEAT

#104 [BE][UP-146] 무비로그 유효성 검사 추가, 닉네임과 프로필 사진만 변경 가능한 api
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/jpa/user/User.java
Labels: FEAT

#105 [BE][UP-138] SSE 알림 구현
  src/main/java/com/ureca/picky_be/PickyBeApplication.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationEventListener.java
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationUseCase.java
  src/main/java/com/ureca/picky_be/base/business/notification/dto/BoardCreatedEvent.java
  src/main/java/com/ureca/picky_be/base/business/notification/dto/CreateNotificationResp.java
  src/main/java/com/ureca/picky_be/base/business/notification/dto/NotificationProjection.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/NotificationDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieLikeRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/notification/EmitterRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/notification/EmitterRepositoryImpl.java
  src/main/java/com/ureca/picky_be/base/persistence/notification/NotificationRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/notification/NotificationController.java
  src/main/java/com/ureca/picky_be/config/AsyncConfig.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/notification/Notification.java
  src/main/java/com/ureca/picky_be/jpa/notification/NotificationType.java
Labels: FEAT

#110 [BE][UP-146] S3설정 수정
  src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java
  src/main/java/com/ureca/picky_be/config/S3Config.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FIX

#112 [BE][UP-161] 마이페이지용 닉네임으로 사용자 한줄평 조회 API
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewLikeService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewUseCase.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GetUserLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewMovieInfo.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/MyPageLineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/UserLineReviewsReq.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/user/UserRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#113 [BE][UP-162] 마이페이지 좋아요 누른 영화들 조회 API 구현
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetUserLikeMovieReq.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetUserLikeMovieResp.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieLikeRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#116 [BE][UP-172] Board 무한 스크롤링 Cursor 기반으로 리팩토링
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/BoardMovieIdQueryReq.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/jpa/board/BoardComment.java
Labels: FEAT

#117 [BE][UP-172] PlayList Cursor 페이징 Validation 추가
  src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java
Labels: FEAT

#119 [BE][UP-174] 장르별 영화 모아보기 무한스크롤 List -> Slice로 변경
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
Labels: FEAT

#122 [BE][UP-176] 마이페이지 유저 닉네임으로 작성 게시글 수, 팔로워 수, 팔로잉 수 조회 API
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/GetMyPageUserInfoResp.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/follow/FollowRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/user/UserRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/jpa/follow/Follow.java
Labels: FEAT

#123 [BE][UP-175] 영화 등록시 영화 플랫폼도 함께 입력 받기
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieReq.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/PlatformRepository.java
  src/main/java/com/ureca/picky_be/jpa/platform/PlatformType.java
Labels: FEAT

#124 [BE][UP-175] 영화 수정에 상영 플랫폼 추가 및 영화 이미 존재하면 다시 추가 막기
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/UpdateMovieReq.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/PlatformRepository.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#125 [BE][UP-175] 영화 상세 조회에 플랫폼 정보 추가
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/PlatformRepository.java
Labels: FEAT

#127 [BE][UP-181] 영화 상세페이지에 총평점 추가
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
Labels: FEAT

#128 [BE][UP-181] 무비로그 조회시 작성자의 프로필 조회하는 presign url 설정
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#130 [BE][UP-183] Recommend entity 생성
  src/main/java/com/ureca/picky_be/jpa/recommend/Recommend.java
Labels: FEAT

#131 [BE][UP-176] 영화 상세페이지 한줄평 요약 정보 조회 API
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewUseCase.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GenderLineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GetLineReviewGenderInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GetLineReviewRatingInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/RatingLineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#133 [BE][UP-187] 한줄평 요약 정보 API Swagger 설명 추가
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
Labels: FEAT

#136 [BE][UP-181] 추천목록 조회해 영화 자동 등록 및 프로필 수정 로직 수정
  .github/workflows/picky-backend-ci-cd.yml
  .gitignore
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieAuto.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieReq.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/implementation/content/ImageManager.java
  src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java
  src/main/java/com/ureca/picky_be/base/implementation/content/VideoManager.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/RecommendRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
  src/main/java/com/ureca/picky_be/jpa/movie/Movie.java
  src/main/resources/application.yml
Labels: FEAT, FIX

#135 [BE][UP-189] LineReview 관련 조회 API들에 isAuthor 추가
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GetUserLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/MyPageLineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/ReadLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
Labels: FEAT

#137 [BE][UP-189] 리뷰 조회시 isAuthor response 추가
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardCommentProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/GetAllBoardCommentsResp.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
Labels: FEAT

#140 [BE][UP-167] 엘라스틱 서치 환경 설정
  .github/workflows/picky-backend-ci-cd.yml
  .gitignore
  docker-compose.yml
  src/main/java/com/ureca/picky_be/global/exception/GlobalExceptionHandler.java
Labels: FEAT

#143 [BE][UP-181] 닉네임 로직 수정
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
Labels: FEAT

#144 [BE][UP-181] 프로필 변경
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
Labels: FEAT

#145 [BE][UP-181] 영화 수정 로직 수정
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieBehindVideoRepository.java
  src/main/java/com/ureca/picky_be/jpa/entity/movie/Movie.java
Labels: FIX

#146 [BE][UP-email] 알림들 조회 및 읽음 업데이트 API 개발
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationUseCase.java
  src/main/java/com/ureca/picky_be/base/business/notification/dto/CreateNotificationResp.java
  src/main/java/com/ureca/picky_be/base/business/notification/dto/NotificationProjection.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/NotificationDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java
  src/main/java/com/ureca/picky_be/base/persistence/notification/NotificationRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/notification/NotificationController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
Labels: FEAT

#149 [BE][UP-181] 추천에 따른 영화 자동 저장 로직 수정
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
Labels: FEAT

#151 [BE][UP-SSE] SSE 연결 메세지 수정
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java
  src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java
Labels: FIX

#155 [BE][UP-Follow] 팔로우 CRUD 기능
  src/main/java/com/ureca/picky_be/base/business/follow/FollowService.java
  src/main/java/com/ureca/picky_be/base/business/follow/FollowUseCase.java
  src/main/java/com/ureca/picky_be/base/business/follow/dto/FollowProjection.java
  src/main/java/com/ureca/picky_be/base/business/follow/dto/GetFollowUserResp.java
  src/main/java/com/ureca/picky_be/base/implementation/follow/FollowManager.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/persistence/follow/FollowRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/follow/FollowController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/entity/follow/Follow.java
Labels: FEAT

#156 [BE][UP-Email] 회원가입, 이벤트용 이메일 전송 API
  src/main/java/com/ureca/picky_be/base/business/email/MailService.java
  src/main/java/com/ureca/picky_be/base/business/email/MailUseCase.java
  src/main/java/com/ureca/picky_be/base/business/email/dto/EventMessageReq.java
  src/main/java/com/ureca/picky_be/base/implementation/email/EmailManager.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/email/EmailController.java
  src/main/java/com/ureca/picky_be/config/AsyncConfig.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FEAT

#158 [BE][UP-LineReview] 한줄평 관련 수정
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewLikeService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewLikeUseCase.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewLikeReq.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/GetMyPageUserInfoResp.java
  src/main/java/com/ureca/picky_be/base/business/user/dto/UserInfoProjection.java
  src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java
  src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewLikeManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/persistence/user/UserRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewLikeController.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
  src/main/java/com/ureca/picky_be/jpa/entity/lineReview/LineReviewLike.java
Labels: FEAT

#161 [BE][UP-Follow] following Count 수정
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
Labels: FIX

#162 [BE][UP-Follow] 팔로워, 팔로잉 카운트 수정
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
Labels: FEAT

#163 [BE][UP-linereview-feat] 한줄평 삭제 구현
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewUseCase.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewLikeManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
  src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
Labels: FEAT

#165 [BE][UP-follow] Follow API Security Config 추가
  src/main/java/com/ureca/picky_be/base/presentation/controller/follow/FollowController.java
  src/main/java/com/ureca/picky_be/config/SecurityConfig.java
Labels: FIX

#166 [BE][UP-linereview-feat] 한줄평 좋아요 싫어요 여부 확인
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewProjection.java
  src/main/java/com/ureca/picky_be/base/business/lineReview/dto/ReadLineReviewResp.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
Labels: FEAT

#168 [BE][UP-LineReview] 마이페이지 게시글들 및 알림 S3 URL 수정
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationEventListener.java
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationUseCase.java
  src/main/java/com/ureca/picky_be/base/business/notification/dto/NotificationProjection.java
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/NotificationDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java
  src/main/java/com/ureca/picky_be/base/persistence/notification/NotificationRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/notification/NotificationController.java
Labels: FIX

#169 [BE][UP-recommend-feat] 추천 목록 플랫폼, 장르 반환
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetRecommendMovieProjection.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetRecommendMovieResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
Labels: FEAT

#170 [BE][UP-recommend-feat] 추천 목록 플랫폼, 장르 반환 파일 추가
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetPlatform.java
Labels: FEAT

#172 [BE][UP-Profile] 프로필 수정 예외 처리
  src/main/java/com/ureca/picky_be/base/business/user/UserService.java
  src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
  src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
Labels: FIX

#174 [BE][UP-linereview-fix] 영화상세페이지 한줄평 토탈 반환
  src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
Labels: FEAT

#175 [BE][UP-linereview-fix] 영화상세페이지 한줄평 토탈 반환 수정
  src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
  src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
Labels: FIX

#178 [BE][UP-191] 장르별 영화 조회 수정
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieProjection.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
  src/main/java/com/ureca/picky_be/jpa/entity/movie/Movie.java
Labels: FIX

#179 [BE][UP-191] 트레일러, ost 수정되지 않는 문제 수정
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
Labels: FIX

#181 [BE][UP-191] 플레이리스트 제목 수정 안 되는 문제 해결
  src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistService.java
  src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java
  src/main/java/com/ureca/picky_be/jpa/entity/playlist/Playlist.java
Labels: FIX

#185 [BE][UP-193] 게시글 조회 관련해서 movieId 추가
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
Labels: FIX

#188 [BE][UP-195] 알림 createdAt 로 수정
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/NotificationDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java
Labels: FIX

#190 알림 Listener 비동기 전략 수정
  src/main/java/com/ureca/picky_be/base/business/notification/NotificationEventListener.java
  src/main/java/com/ureca/picky_be/base/business/notification/dto/BoardCreatedEvent.java
  src/main/java/com/ureca/picky_be/base/implementation/email/EmailManager.java
  src/main/java/com/ureca/picky_be/config/AsyncConfig.java
  src/main/resources/application.yml
Labels: FIX

#193 [BE][UP-197] 이메일 API 토큰 파라미터로 수정
  src/main/java/com/ureca/picky_be/base/business/email/MailService.java
  src/main/java/com/ureca/picky_be/base/business/email/MailUseCase.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/email/EmailController.java
Labels: FIX

#199 [BE][UP-200] Top 10, 장르별 영화, 플레이리스트 조회에 댓글 수 구현
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieProjection.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
Labels: FIX

#200 [BE][UP-199] 엘라스틱 서치 장르, 국가, 반환
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSearchMoviesResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
  src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
  src/main/java/com/ureca/picky_be/elasticsearch/document/movie/MovieDocument.java
Labels: FEAT

#201 [BE][UP-198] 무비로그 조회시, 상영 일자 , 장르들 출력
  src/main/java/com/ureca/picky_be/base/business/board/BoardService.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java
  src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java
  src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
  src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
Labels: FIX

#202 [BE][UP-199] 엘라스틱 서치 오토 세이브시 장르 저장
  src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
  src/main/java/com/ureca/picky_be/elasticsearch/document/movie/MovieDocument.java
Labels: FEAT

#204 [BE][UP-201] 팔로워, 팔로잉 무한스크롤 조회
  src/main/java/com/ureca/picky_be/base/business/follow/FollowService.java
  src/main/java/com/ureca/picky_be/base/implementation/follow/FollowManager.java
  src/main/java/com/ureca/picky_be/base/persistence/follow/FollowRepository.java
  src/main/java/com/ureca/picky_be/base/presentation/controller/follow/FollowController.java
Labels: FIX
